### ISSUE TITLE
preferences page isn't displaying

### ISSUE THREAD

**Issue by masukomi** [asnewman/just-read-firefox#2]
The preferences tab isn't showing, and there's no pop-up appearing on install.
This applies to the version on Firefox Add-ons AND the version here on github. 

see screenshot. 
![CleanShot 2024-08-18 at 08 27 15@2x](https://github.com/user-attachments/assets/59a8061c-86bc-449f-bfa3-d6dc2267dd2b)

this compounds the problem noted in Issue #1 

As an aside: I encountered this in one of my extensions too, and if i can remember how I fixed it, I'll add a note here.

**Comment by asnewman** [comment]
Hi @masukomi, thanks for submitting the issue. The utterance speed you mentioned in #1 can be accessed by clicking on the extension in the toolbar as shown here:
![image](https://github.com/user-attachments/assets/f5aa1092-1b95-4248-8527-2808ccd68000)

That being said, it makes sense to have it in the preference pane (rather than this awful UI I scrapped together), so I'll work on getting the preferences tab to work correctly.

**Comment by masukomi** [comment]
as of v1.2 i can confirm that preferences page is displaying for me.
HOWEVER 
- nothing appears when i click the extension icon & no errors or any other messages appear in the multiprocess browser console when I click it.
- the preferences page has a number input instead of a slider (see screenshot). I dunno if that's a bug or if it's intentional.

Same results in Firefox & Waterfox

![CleanShot 2024-08-26 at 10 28 38@2x](https://github.com/user-attachments/assets/b2d66fa9-9869-4459-a0d6-e71574bb1508)

**Comment by asnewman** [comment]
Both are expected! I removed the panel from the extension icon in favor of the preference pane in the extension settings and changed the setting to a numeral input for finer-grain control.
